export default {
  Artists: [
    "Damien Hirst",
    "Salvador Dali",
    "Pablo Picasso",
    "Vincent Van Gogh",
    "Claude Monet",
    "Andy Warhol",
    "Leonardo da Vinci",
    "Michelangelo",
    "Banksy",
    "Mark Rothko",
    "Keith Haring",
    "Jeff Koons",
    "Rembrandt",
    "Jackson Pollock",
    "Edward Hopper",
    "Georgia O'Keeffe",
  ],
  Authors: [
    "Shakespeare",
    "Tolkien",
    "C.S. Lewis",
    "J.K. Rowling",
    "Stephen King",
    "Ernest Hemingway",
    "Edgar Allan Poe",
    "Charles Dickens",
    "Stephanie Meyer",
    "Tolstoy",
    "Jane Austen",
    "Mark Twain",
    "F. Scott Fitzgerald",
    "John Grisham",
    "Dan Brown",
    "Agatha Christie",
  ],
  Bands: [
    "The Beatles",
    "The Rolling Stones",
    "AC/DC",
    "Nirvana",
    "Backstreet Boys",
    "One Direction",
    "Guns N' Roses",
    "Queen",
    "The Beach Boys",
    "Red Hot Chili Peppers",
    "KISS",
    "Jackson 5",
    "ABBA",
    "The Eagles",
    "The Who",
    "U2",
  ],
  Cartoon: [
    "Garfield",
    "Scooby-Doo",
    "Yogi Bear",
    "Bugs Bunny",
    "Mickey Mouse",
    "Goofy",
    "Jiminy Cricket",
    "Kung Fu Panda",
    "Nemo",
    "Tony the Tiger",
    "Snoopy",
    "Bambi",
    "Dumbo",
    "Toothless",
    "Simba",
    "Sonic the Hedgehog",
  ],
  Civilizations: [
    "Romans",
    "Egyptians",
    "Mayans",
    "Mongols",
    "Aztecs",
    "Japanese",
    "Persians",
    "Greeks",
    "Turks",
    "Vikings",
    "Incas",
    "Spanish",
    "Zulu",
    "Chinese",
    "Spartans",
    "Aliens",
  ],
  Colors: [
    "Red",
    "Blue",
    "Green",
    "Yellow",
    "Black",
    "White",
    "Orange",
    "Pink",
    "Brown",
    "Purple",
    "Gray",
    "Gold",
    "Silver",
    "Bronze",
    "Rainbow",
    "Cream",
  ],
  Food: [
    "Curry",
    "Chips",
    "Salad",
    "Fish",
    "Chicken",
    "Sausage",
    "Orange",
    "Mango",
    "Leek",
    "Tomato",
    "Chilli",
    "Beef",
    "Pizza",
    "Pasta",
    "Ice cream",
    "Chocolate",
  ],
  Capitals: [
    "London",
    "Moscow",
    "Paris",
    "Berlin",
    "Madrid",
    "Rome",
    "Cairo",
    "Helsinki",
    "Stockholm",
    "Oslo",
    "Washington",
    "Mexico city",
    "Bejing",
    "Tokyo",
    "Seoul",
    "Vienna",
  ],
  Rooms: [
    "Hallway",
    "Kitchen",
    "Dining room",
    "Sitting room",
    "Bathroom",
    "Bedroom",
    "Cellar",
    "Attic",
    "Dungeon",
    "Conservatory",
    "Shed",
    "Study",
    "Garage",
    "Music room",
    "Workshop",
    "Gym",
  ],
  Pets: [
    "Dog",
    "Cat",
    "Parrot",
    "Rabbit",
    "Hamster",
    "Guinea pig",
    "Goldfish",
    "Snake",
    "Lizard",
    "Horse",
    "Alpaca",
    "Frog",
    "Rat",
    "Crab",
    "Budgie",
    "Spider",
  ],
  Harry: [
    "Harry Potter",
    "Ron Weasley",
    "Hermione Granger",
    "Neville Longbottom",
    "Luna Lovegood",
    "Albus Dumbledore",
    "Minerva Mcgonnagal",
    "Pomona Sprout",
    "Severus Snape",
    "Dobby",
    "Sirius Black",
    "Remus Lupin",
    "Peter Pettigrew",
    "Lord Voldemort",
    "Draco Malfoy",
    "Rubeus Hagrid",
  ],
  "Marvel Heroes": [
    "Spiderman",
    "Ironman",
    "Hulk",
    "Captain America",
    "Thor",
    "Deadpool",
    "Wolverine",
    "Groot",
    "Loki",
    "Star-lord",
    "Gamora",
    "Drax",
    "Magneto",
    "Ant Man",
    "Daredevil",
    "Charles Xavier",
  ],
  Disney: [
    "Cinderella",
    "Belle",
    "Snow White",
    "Ariel",
    "Mulan",
    "Jasmine",
    "Pocahontas",
    "Mickey Mouse",
    "Donald Duck",
    "Pluto",
    "Bambi",
    "Peter Pan",
    "Captain Hook",
    "Baloo",
    "Winnie the Pooh",
    "Aladdin",
  ],
  Sea: [
    "Starfish",
    "Shark",
    "Whale",
    "Dolphin",
    "Cod",
    "Jellyfish",
    "Seahorse",
    "Puffer fish",
    "Orka",
    "Coral",
    "Oysters",
    "Mussels",
    "Octopus",
    "Kraken",
    "Turtle",
    "Seal",
  ],
  Sports: [
    "Football",
    "Rugby",
    "Athletics",
    "Swimming",
    "Hockey",
    "Tennis",
    "Badminton",
    "Golf",
    "Squash",
    "Gymnastics",
    "Trampolining",
    "Cycling",
    "Volleyball",
    "Cricket",
    "Baseball",
    "Basketball",
  ],
  Hobbies: [
    "Stamps",
    "Trains",
    "Model Making",
    "Knitting",
    "Fishing",
    "Reading",
    "Painting",
    "Gardening",
    "Sailing",
    "Travel",
    "Walking",
    "Pottery",
    "Cooking",
    "Yoga",
    "Photography",
    "Hiking",
  ],
  School: [
    "Maths",
    "Chemistry",
    "Physics",
    "Biology",
    "History",
    "Philosophy",
    "Geography",
    "English",
    "Economics",
    "French",
    "Art",
    "Music",
    "Physical education",
    "Latin",
    "Religious studies",
    "Technology",
  ],
  Transport: [
    "Plane",
    "Car",
    "Tank",
    "Helicopter",
    "Cruise ship",
    "Hovercraft",
    "Motorbike",
    "Bus",
    "Segway",
    "Cable car",
    "Jet ski",
    "Hot air balloon",
    "Train",
    "Spaceship",
    "Magic carpet",
    "Broomstick",
  ],
  Jobs: [
    "Fisherman",
    "Lumberjack",
    "Nurse",
    "Waiter",
    "Lighthouse keeper",
    "Secretary",
    "Accountant",
    "Teacher",
    "Lorry driver",
    "Security guard",
    "Chef",
    "Architect",
    "Police officer",
    "Lawyer",
    "Carpenter",
    "Butcher",
  ],
  Geography: [
    "Lake",
    "Sea",
    "Valley",
    "Mountain",
    "River",
    "Desert",
    "Ocean",
    "Forest",
    "Jungle",
    "Island",
    "Glacier",
    "Waterfall",
    "Volcano",
    "Cave",
    "Arctic",
    "Swamp",
  ],
};
