const wordSheet = {
  Artists: [
    'Damien Hirst',
    'Salvador Dali',
    'Pablo Picasso',
    'Vincent Van Gogh',
    'Claude Monet',
    'Andy Warhol',
    'Leonardo da Vinci',
    'Michelangelo',
    'Banksy',
    'Mark Rothko',
    'Keith Haring',
    'Jeff Koons',
    'Rembrandt',
    'Jackson Pollock',
    'Edward Hopper',
    "Georgia O'Keeffe",
  ],
  Authors: [
    'Shakespeare',
    'Tolkien',
    'C.S. Lewis',
    'J.K. Rowling',
    'Stephen King',
    'Ernest Hemingway',
    'Edgar Allan Poe',
    'Charles Dickens',
    'Stephanie Meyer',
    'Tolstoy',
    'Jane Austen',
    'Mark Twain',
    'F. Scott Fitzgerald',
    'John Grisham',
    'Dan Brown',
    'Agatha Christie',
  ],
  Bands: [
    'The Beatles',
    'The Rolling Stones',
    'AC/DC',
    'Nirvana',
    'Backstreet Boys',
    'One Direction',
    "Guns N' Roses",
    'Queen',
    'The Beach Boys',
    'Red Hot Chili Peppers',
    'KISS',
    'Jackson 5',
    'ABBA',
    'The Eagles',
    'The Who',
    'U2',
  ],
  Capitals: [
    'London',
    'Moscow',
    'Paris',
    'Berlin',
    'Madrid',
    'Rome',
    'Cairo',
    'Helsinki',
    'Stockholm',
    'Oslo',
    'Washington',
    'Mexico city',
    'Bejing',
    'Tokyo',
    'Seoul',
    'Vienna',
  ],
  'Cartoon Animals': [
    'Garfield',
    'Scooby-Doo',
    'Yogi Bear',
    'Bugs Bunny',
    'Mickey Mouse',
    'Goofy',
    'Jiminy Cricket',
    'Kung Fu Panda',
    'Nemo',
    'Tony the Tiger',
    'Snoopy',
    'Bambi',
    'Dumbo',
    'Toothless',
    'Simba',
    'Sonic the Hedgehog',
  ],
  Civilizations: [
    'Romans',
    'Egyptians',
    'Mayans',
    'Mongols',
    'Aztecs',
    'Japanese',
    'Persians',
    'Greeks',
    'Turks',
    'Vikings',
    'Incas',
    'Spanish',
    'Zulu',
    'Chinese',
    'Spartans',
    'Aliens',
  ],
  Colors: [
    'Red',
    'Blue',
    'Green',
    'Yellow',
    'Black',
    'White',
    'Orange',
    'Pink',
    'Brown',
    'Purple',
    'Gray',
    'Gold',
    'Silver',
    'Bronze',
    'Rainbow',
    'Cream',
  ],
  Countries: [
    'U.K.',
    'Spain',
    'Japan',
    'Brazil',
    'France',
    'U.S.A.',
    'Italy',
    'Australia',
    'Germany',
    'Mexico',
    'India',
    'Israel',
    'Canada',
    'China',
    'Russia',
    'Egypt',
  ],
  Disney: [
    'Cinderella',
    'Belle',
    'Snow White',
    'Ariel',
    'Mulan',
    'Jasmine',
    'Pocahontas',
    'Mickey Mouse',
    'Donald Duck',
    'Pluto',
    'Bambi',
    'Peter Pan',
    'Captain Hook',
    'Baloo',
    'Winnie the Pooh',
    'Aladdin',
  ],
  Drinks: [
    'Coffee',
    'Tea',
    'Lemonade',
    'Coca-Cola',
    'Wine',
    'Beer',
    'Punch',
    'Tequila',
    'Hot Chocolate',
    'Milkshake',
    'Root Beer',
    'Water',
    'Smoothie',
    'Orange Juice',
    'Milk',
    'Champagne',
  ],
  'Fairy Tales': [
    'Cinderella',
    'Goldilocks',
    'Jack and the Beanstalk',
    'Hare and the Tortoise',
    'Snow White',
    'Rapunzel',
    'Aladdin',
    'Princess and the Pea',
    'Peter Pan',
    'Little Red Riding Hood',
    'Pinocchio',
    'Beauty and the Beast',
    'Sleeping Beauty',
    'Hansel and Gretel',
    'Gingerbread Man',
    'Three Little Pigs',
  ],
  'Fictional Characters': [
    'Indiana Jones',
    'Mary Poppins',
    'Spiderman',
    'Catwoman',
    'James Bond',
    'Wonder Woman',
    'Princess Leia',
    'The Little Mermaid',
    'Dracula',
    'Lara Croft',
    'Robin Hood',
    'Hermione Granger',
    'Super Mario',
    'Homer Simpson',
    'Hercules',
    'Katniss Everdeen',
  ],
  'Film Genres': [
    'Horror	Action',
    'Thriller',
    'Sci-Fi',
    'Rom-Com',
    'Western',
    'Comedy',
    'Christmas',
    'Gangster',
    'Foreign Language',
    'War',
    'Documentary',
    'Musical',
    'Animation',
    'Zombie',
    'Sport',
  ],
  Food: [
    'Curry',
    'Chips',
    'Salad',
    'Fish',
    'Chicken',
    'Sausage',
    'Orange',
    'Mango',
    'Leek',
    'Tomato',
    'Chilli',
    'Beef',
    'Pizza',
    'Pasta',
    'Ice cream',
    'Chocolate',
  ],
  Games: [
    'Monopoly',
    'Scrabble',
    'Mouse Trap',
    'Guess Who',
    'Risk',
    'Operation',
    'Twister',
    'Pictionary',
    'Battleship',
    'Backgammon',
    'Clue',
    'Chess',
    'Checkers',
    'Trivial Pursuit',
    'Jenga',
    'Hungry Hungry Hippos',
  ],
  Geography: [
    'Lake',
    'Sea',
    'Valley',
    'Mountain',
    'River',
    'Desert',
    'Ocean',
    'Forest',
    'Jungle',
    'Island',
    'Glacier',
    'Waterfall',
    'Volcano',
    'Cave',
    'Arctic',
    'Swamp',
  ],
  'Harry Potter': [
    'Harry Potter',
    'Ron Weasley',
    'Hermione Granger',
    'Neville Longbottom',
    'Luna Lovegood',
    'Albus Dumbledore',
    'Minerva Mcgonnagal',
    'Pomona Sprout',
    'Severus Snape',
    'Dobby',
    'Sirius Black',
    'Remus Lupin',
    'Peter Pettigrew',
    'Lord Voldemort',
    'Draco Malfoy',
    'Rubeus Hagrid',
  ],
  'Historical Figure': [
    'Jesus',
    'Stalin',
    'Hitler',
    'Darwin',
    'Martin Luther King Jr.',
    'Pocahontas',
    'Einstein',
    'Christopher Columbus',
    'Mother Teresa',
    'Ulysses S. Grant',
    'Caesar',
    'Mozart',
    'Cleopatra',
    'Buddha',
    'Churchill',
  ],
  Hobbies: [
    'Stamps',
    'Trains',
    'Model Making',
    'Knitting',
    'Fishing',
    'Reading',
    'Painting',
    'Gardening',
    'Sailing',
    'Travel',
    'Walking',
    'Pottery',
    'Cooking',
    'Yoga',
    'Photography',
    'Hiking',
  ],
  Inventions: [
    'Matches',
    'Gunpowder',
    'Wheel',
    'Printing',
    'Computer',
    'Internet',
    'Compass',
    'Plane',
    'TV',
    'Electricity',
    'Writing',
    'Steam',
    'Engine',
    'Car',
    'Telephone',
    'Camera',
    'Radio',
  ],
  Jobs: [
    'Fisherman',
    'Lumberjack',
    'Nurse',
    'Waiter',
    'Lighthouse keeper',
    'Secretary',
    'Accountant',
    'Teacher',
    'Lorry driver',
    'Security guard',
    'Chef',
    'Architect',
    'Police officer',
    'Lawyer',
    'Carpenter',
    'Butcher',
  ],
  'Marvel Heroes': [
    'Spiderman',
    'Ironman',
    'Hulk',
    'Captain America',
    'Thor',
    'Deadpool',
    'Wolverine',
    'Groot',
    'Loki',
    'Star-lord',
    'Gamora',
    'Drax',
    'Magneto',
    'Ant Man',
    'Daredevil',
    'Charles Xavier',
  ],
  Movies: [
    'Jurassic Park',
    'Jaws',
    'Raiders of the Lost Ark',
    'The Avengers',
    'Transformers',
    'Toy Story',
    'Home Alone',
    'Titanic',
    'E.T.',
    'The Wizard of Oz',
    'King Kong',
    'The Matrix',
    'Shrek',
    'The Godfather',
    'Finding Nemo',
    'Avatar',
  ],
  Music: [
    'Rock',
    'Heavy Metal',
    'Classical',
    'Funk',
    'Hip Hop',
    'Pop',
    'Techno',
    'Blues',
    'Rap',
    'Punk',
    'Indie',
    'Christmas',
    'Country',
    'House',
    'Disco',
    'Reggae',
  ],
  'Musical Instruments': [
    'Electric Guitar',
    'Piano',
    'Violin',
    'Drums',
    'Bass Guitar',
    'Saxophone',
    'Cello',
    'Flute',
    'Clarinet',
    'Trumpet',
    'Voice',
    'Ukulele',
    'Harp',
    'Bagpipes',
    'Harmonica',
    'Banjo',
  ],
  Musicals: [
    'West Side Story',
    'Cats',
    'Jersey Boys',
    'School of Rock',
    'Phantom of the Opera',
    'Les Miserables',
    'Oliver',
    'Hamilton',
    'Chicago',
    'Hadestown',
    'Annie',
    'Book of Mormon',
    'Lion King',
    'Wicked',
    'Hairspray',
    'Mamma Mia',
  ],
  'Mythical Creatures': [
    'Cyclops',
    'Pegasus',
    'Medusa',
    'Sphinx',
    'Werewolf',
    'Unicorn',
    'Dragon',
    'Troll',
    'Loch Ness Monster',
    'Mermaid',
    'Phoenix',
    'Vampire',
    'Minotaur',
    'Hydra',
    'Yeti',
    'Centaur',
  ],
  Pets: [
    'Dog',
    'Cat',
    'Parrot',
    'Rabbit',
    'Hamster',
    'Guinea pig',
    'Goldfish',
    'Snake',
    'Lizard',
    'Horse',
    'Alpaca',
    'Frog',
    'Rat',
    'Crab',
    'Budgie',
    'Spider',
  ],
  Phobias: [
    'Ghosts',
    'Spiders',
    'Monsters',
    'Rats',
    'Toilets',
    'Snakes',
    'Germs',
    'Clowns',
    'Needles',
    'Dogs',
    'Birds',
    'Insects',
    'Children',
    'Shadows',
    'Roller Coasters',
    'Planes',
  ],
  Presidents: [
    'Clinton',
    'Reagan',
    'Roosevelt (FDR)',
    'Eisenhower',
    'George W. Bush',
    'George Bush Sr.',
    'Obama',
    'Trump',
    'Kennedy',
    'Lincoln',
    'Washington',
    'Nixon',
    'Teddy Roosevelt',
    'Jefferson',
    'Adams',
    'Carter',
  ],
  Rooms: [
    'Hallway',
    'Kitchen',
    'Dining room',
    'Sitting room',
    'Bathroom',
    'Bedroom',
    'Cellar',
    'Attic',
    'Dungeon',
    'Conservatory',
    'Shed',
    'Study',
    'Garage',
    'Music room',
    'Workshop',
    'Gym',
  ],
  School: [
    'Maths',
    'Chemistry',
    'Physics',
    'Biology',
    'History',
    'Philosophy',
    'Geography',
    'English',
    'Economics',
    'French',
    'Art',
    'Music',
    'Physical education',
    'Latin',
    'Religious studies',
    'Technology',
  ],
  Sea: [
    'Starfish',
    'Shark',
    'Whale',
    'Dolphin',
    'Cod',
    'Jellyfish',
    'Seahorse',
    'Puffer fish',
    'Orka',
    'Coral',
    'Oysters',
    'Mussels',
    'Octopus',
    'Kraken',
    'Turtle',
    'Seal',
  ],
  'Sci-Fi/Fantasy': [
    'Star Wars',
    'Lord of the Rings',
    'Star Trek',
    'Blade Runner',
    'The Addams Family',
    '2001: A Space Odyssey',
    'Terminator',
    'Game of Thrones',
    'Dune',
    'The Princess Bride',
    'Alice in Wonderland',
    'The Avengers',
    'The War of the Worlds',
    'The Martian',
    'WALL-E',
    'Edward Scissorhands',
  ],
  Sports: [
    'Football',
    'Rugby',
    'Athletics',
    'Swimming',
    'Hockey',
    'Tennis',
    'Badminton',
    'Golf',
    'Squash',
    'Gymnastics',
    'Trampolining',
    'Cycling',
    'Volleyball',
    'Cricket',
    'Baseball',
    'Basketball',
  ],
  'Sports Stars': [
    'Tiger Woods',
    'Pele',
    'Michael Jordan',
    'LeBron James',
    'Michael Phelps',
    'Serena Williams',
    'Muhammad Ali',
    'Tom Brady',
    'Hope Solo',
    'Babe Ruth',
    'Wayne Gretzky',
    'Ronda Rousey',
    'Tony Hawk',
    'Shaun White',
    'Usain Bolt	Dwayne "The Rock" Johnson',
  ],
  States: [
    'California',
    'Texas',
    'Alabama',
    'Hawaii',
    'Florida',
    'Montana',
    'Nevada',
    'Mississippi',
    'North Carolina',
    'New York',
    'Kentucky',
    'Tennessee',
    'Colorado',
    'Washington',
    'Illinois',
    'Alaska',
  ],
  'The Arts': [
    'Painting',
    'Sculpture',
    'Architecture',
    'Dance',
    'Literature',
    'Opera',
    'Stand-up',
    'Comic Books',
    'Illustration',
    'Music',
    'Theatre',
    'Cinema',
    'Video Games',
    'Graffiti',
    'Fashion',
    'Photography',
  ],
  Toys: [
    'Lego',
    'Rocking Horse',
    'Super Soaker',
    'Cabbage Patch Dolls',
    "Rubik's Cube",
    'Etch a Sketch',
    'Teddy Bear',
    'Play Doh',
    'Yo-yo',
    'Frisbee',
    'Hot Wheels',
    'Barbie',
    'Slinky',
    'G.I. Joe',
    'Hula Hoop',
    'Furby',
  ],
  Transport: [
    'Plane',
    'Car',
    'Tank',
    'Helicopter',
    'Cruise ship',
    'Hovercraft',
    'Motorbike',
    'Bus',
    'Segway',
    'Cable car',
    'Jet ski',
    'Hot air balloon',
    'Train',
    'Spaceship',
    'Magic carpet',
    'Broomstick',
  ],
  'TV Shows': [
    'Friends',
    'Sex and the City',
    'Star Trek',
    'The Walking Dead',
    'Breaking Bad',
    'Days of our Lives',
    'How I Met Your Mother',
    'Lost',
    'The Office',
    'The X-Files',
    'General Hospital',
    'Frasier',
    'Mad Men',
    'South Park',
    'Game of Thrones',
    'Golden Girls',
  ],
  'Under the Sea': [
    'Octopus',
    'Starfish',
    'Shark',
    'Jellyfish',
    'Lobster',
    'Seal',
    'Dolphin',
    'Killer Whale',
    'Crab',
    'Giant Squid',
    'Seahorse',
    'Stingray',
    'Sea Turtle',
    'Clownfish',
    'Swordfish',
    'Mermaid',
  ],
  'Wedding Anniversaries': [
    'Wood',
    'China',
    'Paper',
    'Cotton',
    'Bronze',
    'Gold',
    'Ruby',
    'Diamond',
    'Crystal',
    'Flowers',
    'Silk',
    'Leather',
    'Pearl',
    'Coral',
    'Tin',
    'Wool',
  ],
  'World Wonders': [
    'Pyramids',
    'Eiffel Tower',
    'Statue of Liberty',
    'Big Ben',
    'Stonehenge',
    'Golden Gate Bridge',
    'Colosseum',
    'Sydney Opera House',
    'Christ the Redeemer',
    'Machu Picchu',
    'Taj Mahal',
    'Hoover Dam',
    'Great Wall of China',
    'Mount Rushmore',
    'Empire State Building',
    'Leaning Tower of Pisa',
  ],
  Zoo: [
    'Elephant',
    'Giraffe',
    'Koala',
    'Tiger',
    'Lion',
    'Leopard',
    'Meerkat',
    'Buffalo',
    'Ostrich',
    'Owl',
    'Eagle',
    'Parrot',
    'Scorpion',
    'Alligator',
    'Zebra',
    'Gorilla',
  ],
};

module.exports = wordSheet;
